model:
  default: Qwen/Qwen3-Max
  provider: custom
  base_url: https://api.modelverse.cn/v1
  api_key: nFzDY6ygaRWnDrQL1eA11aB2-4294-4284-885A-B7Ac3dE0
agent:
  max_turns: 200
  api_max_retries: 3
terminal:
  cwd: /Users/user/Documents/Code/work/mywiki/raw
kanban:
  max_in_progress_per_profile: 3
onboarding:
  seen:
    tool_progress_prompt: true